<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="113645" started-at="2020-02-10T21:11:09Z" finished-at="2020-02-10T21:13:02Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:TestRunner.SaleforceRunner@39c0f4a]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="113645" started-at="2020-02-10T21:11:09Z" finished-at="2020-02-10T21:13:02Z">
      <class name="TestRunner.SaleforceRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:TestRunner.SaleforceRunner@39c0f4a]" name="setUpClass" is-config="true" duration-ms="250" started-at="2020-02-10T13:11:09Z" finished-at="2020-02-10T13:11:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:TestRunner.SaleforceRunner@39c0f4a]" name="feature" duration-ms="112895" started-at="2020-02-10T13:11:09Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2020-02-10T13:13:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sales Force Test Cases]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [Please check your username and password. If you still can't log in, contact your Salesforce administra] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Please check your username and password. If you still can't log in, contact your Salesforce administra] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Please check your username and password. If you still can't log in, contact your Salesforce administra] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Resources.Resuable.validateText(Resuable.java:32)
	at salesforce.SalesForcePageObject.loginPage.getErrorMessage(loginPage.java:38)
	at StepDefinition.StepDefinition.validate_the_message(StepDefinition.java:69)
	at âœ½.Then : Validate the message "Please check your username and password. If you still can't log in, contact your Salesforce administra"(C:/Java_Anitha/SalesForcePageObject/src/test/java/Feature/Salesforce.Feature:64)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:TestRunner.SaleforceRunner@39c0f4a]" name="tearDownClass" is-config="true" duration-ms="396" started-at="2020-02-10T13:13:02Z" finished-at="2020-02-10T13:13:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- TestRunner.SaleforceRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
