<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mapkhome" name="TestRunner.SaleforceRunner" tests="1" failures="1" timestamp="10 Feb 2020 21:13:04 GMT" time="112.895" errors="0">
  <testcase name="feature" time="112.895" classname="TestRunner.SaleforceRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [Please check your username and password. If you still can&#039;t log in, contact your Salesforce administra] but found [Please check your username and password. If you still can&#039;t log in, contact your Salesforce administrator.]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Please check your username and password. If you still can't log in, contact your Salesforce administra] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Please check your username and password. If you still can't log in, contact your Salesforce administra] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Resources.Resuable.validateText(Resuable.java:32)
	at salesforce.SalesForcePageObject.loginPage.getErrorMessage(loginPage.java:38)
	at StepDefinition.StepDefinition.validate_the_message(StepDefinition.java:69)
	at ?.Then : Validate the message "Please check your username and password. If you still can't log in, contact your Salesforce administra"(C:/Java_Anitha/SalesForcePageObject/src/test/java/Feature/Salesforce.Feature:64)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- TestRunner.SaleforceRunner -->
